[project]
name = 'digital-inheritance'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.asset-will]
path = 'contracts/asset-will.clar'
clarity_version = 2
epoch = 2.5

[contracts.sip-009-trait-nft-standard]
path = 'contracts/sip-009-trait-nft-standard.clar'
clarity_version = 2
epoch = 2.5

[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
